### ISSUE TITLE
Access lesson creation page - backend too

### ISSUE THREAD

**Issue by bgrunes** [SWE-Group-2F/Sapphire-Project17-2f#1]
**User Story:** As a teacher, I want to easily access lesson creation, so that I can focus on generating content for the lesson.

**Acceptance Criteria:**

- [x] 1. Lesson is saved to teacher profile when created
- [x] 2. Lessons can be reverted to their original form.

**Tasks**:
- [x] 1. Server routes, models, controllers [2.5]
- [x] 2. Client Controller, routes [2.5]
- [x] 3. Pulling products into client views correctly and view adjustment [2]
- [x] 4. Watching tutorials [2]
- [ ] 5. add ability to publicize and privatize lessons

**Comment by bgrunes** [comment]
11/2/2023

- Encapsulated the classrooms page into a tab
- Worked on lesson tab but had issues

11/3/2023
- Fixed issues with Lessons tab
- Added Strapi permissions for Mentor/Teachers so lessons can be added to the lessons tab
- Next Goal: Add Edit lesson Feature to Lessons list

**Comment by bgrunes** [comment]
11/13/2023

Tested code through Sonar Cloud - No issues besides already enclosed bugs and smells from previous devs.

**Comment by bgrunes** [comment]
https://docs.google.com/presentation/d/1DILUWX2_N5pv4dzx4wM5AFLULxmCh-cp1upRjxqAWhI/edit#slide=id.g292e05c1701_0_122

**Comment by bgrunes** [comment]
11/20 - 11/30

Lesson Reversion works perfectly, needs to be cleaned up on the front-end and needs to only show the specified lesson's version history, but shows all history at the current state.
