### ISSUE TITLE
As a teacher, I want to instantiate rosters and emojis from an uploaded csv file, so I can easily augment the roster with a large amount of students to save time.

### ISSUE THREAD

**Issue by bgrunes** [SWE-Group-2F/Sapphire-Project17-2f#10]
**Acceptance Criteria:**

- [ ] Student names in roster have links that go to their saved body of work / workspace
- [ ] The student roster contains an additional dropdown option for assigning a student to a class the teacher created.
- [ ] The student roster has a column of “transfer” buttons per student that opens up a drop-down menu to choose which class to transfer them to.

**Tasks:**
- [x] 1. Debug the text to emoji issue when reading csv files to the server [1.5]
- [x] 2. Change from adding to the roster to removing the old roster and adding the new imported roster [2.5]
- [x] 3. Check and adjust designs for importing files if applicable [1.5]
- [x] 4. watching tutorials [2]

**Comment by Andrew-Kohler** [comment]
Not sure what we initially planned with the acceptance critera that don't match the title story - maybe a copy-paste that never got edited while were in the mix of setting up for this sprint. Regardless, I've done all the tasks, so this is getting marked as done. 
- Andrew

**Comment by Andrew-Kohler** [comment]
Note that there is currently a bug with the destructive uploading. The most recent progress on the matter can be found on my only remaining branch,
- Andrew
