### ISSUE TITLE
Assign a lesson to a classroom

### ISSUE THREAD

**Issue by bgrunes** [SWE-Group-2F/Sapphire-Project17-2f#2]
**User Story:** As a teacher, I want to associate a lesson with a classroom, so I can teach that lesson to that class.

**Acceptance Criteria:**

- [x] 1. A list of associated lessons can be viewed in the teacher classroom menu
- [x] 2. Lesson creation has a field asking which classroom to associate it with

**Tasks:**

- [x] 1. Familiarize with existing implementation [1]
- [x] 2. Reformat frontend to match wireframes [1.5]
- [x] 3. Add removal features for lessons and units [2]
- [x] 4. Dropdown menus for unit and lesson selection [1]
- [x] 5. Watching tutorials [2]
