### ISSUE TITLE
Group Students in classrooms

### ISSUE THREAD

**Issue by bgrunes** [SWE-Group-2F/Sapphire-Project17-2f#3]
**User Story:** As a teacher, I want to be able to group my students within classrooms, so that their online environment can reflect the teams they may be placed in within the actual classroom environment.

**Acceptance Criteria:**

- [ ] 1. Individual students can be added to groups from student roster
- [ ] 2. Individual students can be removed to groups from student roster
- [ ] 3. Mentors can be incorporated into student groups

**Tasks:**
- [ ] 1. Create 'Groups' tab in classroom view [1]
- [ ] 2. Incorporate popup menu for accessing features [1]
- [ ] 3. Ensure group association data (tags?) (viewable in student roster) [2.5]
- [ ] 4. Make autofill dropdown feature connected to student roster [1.5]
- [x] 5. Watching tutorials [2]
