### ISSUE TITLE
As a teacher, I want to easily access my student roster, so that I can see who is in my classroom.

### ISSUE THREAD

**Issue by bgrunes** [SWE-Group-2F/Sapphire-Project17-2f#4]
**Acceptance Criteria:**

- [ ] 1. Student names in roster have links that go to their saved body of work / workspace
- [ ] 2. The student roster contains an additional dropdown option for assigning a student to a class the teacher created.
- [ ] 3. The student roster has a column of “transfer” buttons per student that opens up a drop-down menu to choose which class to transfer them to.

**Tasks:**
- [x] 1. Incorporate file upload feature [2.5]
- [x] 2. Emoji debugging [1]
- [ ] 3. Transferring between classrooms [2]
- [x] 4. Watching tutorials [2]

**Comment by Andrew-Kohler** [comment]
This is a parent story to some smaller ones we made elaborating on some of these tasks - while it will not be in the active development section, we will be keeping an eye on it this sprint as we make progress on its components. -Andrew
