### ISSUE TITLE
As a teacher, I want to view a roster of other teachers’ classrooms, so that I can look at their lessons and teaching styles.

### ISSUE THREAD

**Issue by bgrunes** [SWE-Group-2F/Sapphire-Project17-2f#5]
**Acceptance Criteria:**

- [x] 1. Teachers can filter the list of classes to see the desired group of classrooms.
- [ ] 2. Teachers can click a “view” button to access all the other teacher’s classrooms.

**Tasks:**
- [x] 1. Add sorting features to classroom page based on classroom content [2.5] 
- [x] 2. Add authorship on classrooms that are not made by current user [1] 
- [ ] 3. Adjust teacher view for looking at classrooms that are not theirs to remove certain editing options [2.5] 
- [x] 4. watching tutorials [2]
- [x]  5. Add ability to publicize or privatize classrooms

**Comment by Andrew-Kohler** [comment]
End of Sprint 1, 11/13: Well, not as far as I wanted to get, but I'm ready to go the rest of the way. Here's to Sprint 2.

**Comment by Andrew-Kohler** [comment]
End of sprint 2: The only thing that doesn't work about this is actually viewing the content of other teachers, which should be resolvable through a simple check of whether the owning mentor is viewing the page, and changing a few role permission in Strapi. The sorting, as far as I can tell, is aces.
