### ISSUE TITLE
As a teacher, I want to be able to access other teachers' lessons to edit and save them to my workspace so I can use them in my class for convenience.

### ISSUE THREAD

**Issue by bgrunes** [SWE-Group-2F/Sapphire-Project17-2f#6]
**Acceptance Criteria:**

- [x] 1. Lessons can be altered & saved after initial creation
- [x] 3. Copied lessons can be reverted to their original form

**Tasks:**

- [x] 1. Watching Tutorials
- [x] 2. Add edit column and buttons to each lesson on teacher 'lessons' tab

**Comment by bgrunes** [comment]
11/27/2023

Added Edit buttons to lessons tab

**Comment by bgrunes** [comment]
third acceptance criteria fits in with lesson reversion (lesson history collection)

**Comment by bgrunes** [comment]
12/4/2023

Noticed bug when submitting an edit where the name of the button is changed to the lesson name
