### ISSUE TITLE
As a teacher, I want to be able to copy another teacher’s lesson into my own profile, so that I can edit it to work for my needs.

### ISSUE THREAD

**Issue by bgrunes** [SWE-Group-2F/Sapphire-Project17-2f#7]
**Acceptance Criteria:**

- [ ] 1. A button/icon is used to create a template of the lesson (another teacher’s) that is saved to the teacher’s profile/workspace.
- [ ] 2. The saved copy can be edited from a lesson storage page.

**Tasks:**

- [ ] 1. Watching tutorials
- [ ] 2. Create button in front-end that links to the creation of the template
- [ ] 3. Create back-end code to create a template
- [ ] 4. Create strapi relative modifications
