### ISSUE TITLE
As a teacher, I want to be able to transfer a student to another class the teacher owns, so that they can access the learning materials they need.

### ISSUE THREAD

**Issue by bgrunes** [SWE-Group-2F/Sapphire-Project17-2f#8]
**Acceptance Criteria:**

- [ ] 1. The student roster has a column of “transfer” buttons per student that opens up a drop-down menu to choose which class to transfer them to.

**Tasks:**
- [ ] 1. Creating frontend transfer menu to complete operation [2]
- [ ] 2. Setting up requests.js and student page to access and duplicate students into other classrooms [2]
- [ ] 3. Transfer option only available for public classrooms [1]
- [ ] 4. watching tutorials [2]

**Comment by Andrew-Kohler** [comment]
While this was intended for Sprint 2, it wasn't a feature I ever got around to. Unfortunate, as it seems theoretically simple to implement.
Oh well.
- Andrew
