### ISSUE TITLE
As a teacher, I want to easily view a student’s work by clicking their name, so I can review and assess their individual work.

### ISSUE THREAD

**Issue by bgrunes** [SWE-Group-2F/Sapphire-Project17-2f#9]
**Acceptance Criteria:**

- [ ] Student names in roster have links that go to their saved body of work / workspace
- [ ] The student roster contains an additional dropdown option for assigning a student to a class the teacher created.
- [ ] The student roster has a column of “transfer” buttons per student that opens up a drop-down menu to choose which class to transfer them to.

**Tasks:**

- [ ] Add the 'view' button to roster
- [ ] Determine how to design pop-up view of student workspace via Profile team (time taken for this task may differ do to possible comm issues)
- [ ] Create view based on Profile team implementation (create a basic view if necessary)
